
package com.earwicker.cppjvm.cppwrap;

import java.lang.reflect.*;
import java.util.*;
import java.io.*;

public abstract class SourceGenerator {
    private PrintWriter writer;
    private Class<?> source;

    public String toString(Class<?> cls) throws Exception {
        source = cls;
        final Writer result = new StringWriter();
        writer = new PrintWriter(result);
        editWarning();
        generate();
        return result.toString();
    }

    protected PrintWriter out() {
        return writer;
    }

    protected Class<?> cls() {
        return source;
    }

    public abstract void generate() throws Exception;

    private void editWarning() {
        out().println();
        out().println("//");
        out().println("// Do not edit this file - it was generated automatically from the Java class:");
        out().println("//");
        out().println("// " + cls().getName());
        out().println("//");
        out().println();
    }

    protected void include(Class<?> cls) {
        if (CppWrap.isWrapped(cls))
            out().println("#include <" + cls.getName().replace('.', '/') + ".hpp>");
    }

    protected void beginNamespace(Class<?> cls) {
        String[] namespaces = cls.getName().split("\\.");
        for (int n = 0; n < (namespaces.length - 1); n++)
            out().print(" namespace " + namespaces[n] + " {");
    }

    protected void endNamespace(Class<?> cls) {
        for (int n = 0; n < cls.getName().split("\\.").length - 1; n++)
            out().print(" }");
        out().println();
    }

    protected static final int DECLARE_TYPES = 0;
    protected static final int CALL_WRAPPED = 1;
    protected static final int CALL_UNWRAPPED = 2; 

    protected void listParameters(Class<?>[] params, int mode) throws Exception {
        int pos = 0;
        for (Class<?> p : params) {
            pos++;
            out().print(
                (pos > 1 ? ", " : "") + 
                (mode == DECLARE_TYPES 
                    ? (CppWrap.isWrapped(p) ? ("const " + CppWrap.cppType(p) + " &") : (CppWrap.cppType(p) + " "))
                    : "") + 
                "args" + pos + 
                (mode == CALL_UNWRAPPED && CppWrap.isWrapped(p) ? ".get_impl()" : "")
            );
        }
    }
}


